myapp/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'user/list'
  post 'adduser' , to: 'user#create'
  get 'user/new'
  get 'pages/index'
  get 'profile' , to: 'pages#show'
  get 'login' , to: 'sessions#new'
  delete 'logout' , to: 'sessions#destroy'
  post 'login' , to: 'sessions#create'
  root 'pages#index'
  get 'destroy' , to: 'user#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

myapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

myapp/app/models/user.rb
class User < ApplicationRecord
	has_secure_password
end

myapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  helper_method :current_user , :logged_in?

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]

  end

  def logged_in?
  	!!current_user
  end

  def check_login
  	if !logged_in?
  		flash[:danger] = "please Login"
  		redirect_to login_path
  	end
  end
end

myapp/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :check_login , only: [:show]

  def index
  end

  def show

  end
end

myapp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user  = User.find_by(email: params[:email])

  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		if user.id == 1
  			flash[:success] = "Welcome to your home page admin"
  		else
  			flash[:success] = "Welcome to your home page"
  		end	
  		redirect_to root_path
  	else
  		flash.now[:danger] = "Your credentials are invalid"
  		render 'new'
  	end
  end

  def destroy
  	session[:user_id] = nil
  	flash.now[:success] = "Hoping to see you soon"
  	redirect_to root_path
  end
end

myapp/app/controllers/user_controller.rb
class UserController < ApplicationController
	def list
		@users = User.all	
	end

	def new

	end

	def create
		user = User.new(name: params[:name] , email: params[:email] ,password: params[:password])
		if user.save
			redirect_to :controller => 'sessions' , :action => 'new'
		else
			render :action => 'new'
		end

	end

	def user_params
		params.require(:user).permit(:name , :email , :password)
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to 'list'
	end

end

myapp/app/helpers/application_helper.rb
module ApplicationHelper
end

myapp/app/helpers/pages_helper.rb
module PagesHelper
end

myapp/app/helpers/sessions_helper.rb
module SessionsHelper
end

myapp/app/helpers/user_helper.rb
module UserHelper
end

myapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<nav class="navbar navbar-inverse navbar-fixed-top">
  		<div class="container">
  			<div class="navbar-header">
  				<%= link_to 'Rails my app' , '#' ,class: 'navbar-brand' %>
  				
  			</div>
  			<div class="collapse navbar-collapse">
  				<ul class="nav navbar-nav navbar-right">
  					<li><%= link_to 'Home' %></li>
  					<% if !logged_in? %> 
  						<li><%= link_to 'Log in' , login_path %></li>
  						<li><%= link_to 'Register', user_new_path %></li> 
  					<% else %>
  						<li><%= link_to 'Profile',profile_path %></li> 
  						<li><%= link_to 'Logout' ,logout_path, method: :delete %></li>
  						<% user = current_user %>
  						<% if user.id == 1 %>
							<li><%= link_to 'all users' , user_list_path %></li>
						<% end %>  
  					<% end %>	

  				</ul>

  			</div>

  		</div>

  	</nav>
<div class="container">
	<% flash.each do |type,message| %>
	<div class="alert alert-<%= type %>"><%= message %>
		
	</div>
	<% end %>
<%= yield %>
</div>
    
  </body>
</html>

myapp/app/views/pages/index.html.erb
<div class="jumbotron">
	<h1>Welcome !</h1>
	
</div>

myapp/app/views/pages/show.html.erb
<div class="row">
	<div class="col-md-6 col md-offset-3">
		<h1>Profile</h1>

		<% user = current_user %>
		<table class="table">
			<tr>
				<th>Name</th>
				<td><%= user.name %></td>
			</tr>
			<tr>
				<th>Email</th>
				<td><%= user.email %></td>
			</tr>
		</table>

	</div>

</div>

myapp/app/views/user/list.html.erb
<% if @users.blank?  %>
<div class="container">
	<p> There are no users in the system </p>

</div>
<% else %>
<div class="container">
	<p> These are the following users </p>
</div>
<div class="row">
	<div class="col-md-6 col md-offset-3">
		<table class="table">
			<tr>
				<th>NAME</th>
				<th>EMAIL</th>
				<th>ID</th>
			</tr>
			<% @users.each do |u| %>
			<tr>
				<td><%= u.name %></td>
				<td><%= u.email %></td>
				<td><%= u.id %></td>
				<td> <%= link_to 'delete user', {:action => 'destroy' ,:id => u.id }%> </td>
			</tr>
			<% end %> 

		</table>

	</div>
	
</div>
<% end %>

myapp/app/views/user/new.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3 well" >
		<%= form_tag '/adduser' do %>
		<div class="form-group">
			<%= label_tag :name %> 
			<%= text_field_tag  :name , nil, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= label_tag :email %> 
			<%= text_field_tag :email , nil, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%=	label_tag :password%>
			<%= text_field_tag :password , nil, class: 'form-control' %> 
			
		</div>
		<%= submit_tag 'Sign Up' , class: 'btn btn-success' %>
		<% end %>
	</div>
</div>